#ifndef GLOBALS_H
#define GLOBALS_H

const int TILE_COUNT    = 8/*BOARD_WIDTH*/  * 8/*BOARD_HEIGHT*/;
const int SCREEN_WIDTH  = 8/*BOARD_WIDTH*/  * 80/*TILE_WIDTH*/;
const int SCREEN_HEIGHT = 8/*BOARD_HEIGHT*/ * 80/*TILE_HEIGHT*/;

enum tiles_t
{
	TILE_NONE = -1,
	TILE_BLACK, TILE_BLACK_SELECTED,
	TILE_WHITE, TILE_WHITE_SELECTED,
	TILE_RED,   TILE_RED_KING,   TILE_RED_SELECTED,   TILE_RED_POSSIBLE,
	TILE_GREEN, TILE_GREEN_KING, TILE_GREEN_SELECTED, TILE_GREEN_POSSIBLE
};

enum directions_t
{
	DIRECTION_NONE = -1,
	DIRECTION_UP,
	DIRECTION_DOWN,
	DIRECTION_LEFT,
	DIRECTION_RIGHT
};

#endif
